// Code generated by "stringer -type=BasicColor"; DO NOT EDIT.

package tcolor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Black-30]
	_ = x[Red-31]
	_ = x[Green-32]
	_ = x[Yellow-33]
	_ = x[Blue-34]
	_ = x[Purple-35]
	_ = x[Cyan-36]
	_ = x[Gray-37]
	_ = x[DarkGray-90]
	_ = x[BrightRed-91]
	_ = x[BrightGreen-92]
	_ = x[BrightYellow-93]
	_ = x[BrightBlue-94]
	_ = x[BrightPurple-95]
	_ = x[BrightCyan-96]
	_ = x[White-97]
}

const (
	_BasicColor_name_0 = "None"
	_BasicColor_name_1 = "BlackRedGreenYellowBluePurpleCyanGray"
	_BasicColor_name_2 = "DarkGrayBrightRedBrightGreenBrightYellowBrightBlueBrightPurpleBrightCyanWhite"
)

var (
	_BasicColor_index_1 = [...]uint8{0, 5, 8, 13, 19, 23, 29, 33, 37}
	_BasicColor_index_2 = [...]uint8{0, 8, 17, 28, 40, 50, 62, 72, 77}
)

func (i BasicColor) String() string {
	switch {
	case i == 0:
		return _BasicColor_name_0
	case 30 <= i && i <= 37:
		i -= 30
		return _BasicColor_name_1[_BasicColor_index_1[i]:_BasicColor_index_1[i+1]]
	case 90 <= i && i <= 97:
		i -= 90
		return _BasicColor_name_2[_BasicColor_index_2[i]:_BasicColor_index_2[i+1]]
	default:
		return "BasicColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
